const sampleData = {
  products: [
    {
      name: "Pioneer DJ DDJ-1000 Controller",
      slug: "pioneer-dj-ddj-1000-controller",
      category: "DJ Controllers",
      description:
        "Professional 4-channel DJ controller with club-style layout",
      images: [
        "/images/sample-products/p1-1.webp",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 1199.99,
      brand: "Pioneer DJ",
      rating: 4.9,
      numReviews: 42,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Roland TR-8S Rhythm Performer",
      slug: "roland-tr-8s-rhythm-performer",
      category: "Drum Machines",
      description:
        "Flagship drum machine with legendary TR sounds and custom samples",
      images: [
        "/images/sample-products/p2-1.webp",
        "/images/sample-products/p2-2.jpeg",
      ],
      price: 799.99,
      brand: "Roland",
      rating: 4.8,
      numReviews: 35,
      stock: 8,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Korg Minilogue XD Synthesizer",
      slug: "korg-minilogue-xd-synthesizer",
      category: "Synthesizers",
      description:
        "Versatile analog synthesizer with digital multi-engine and effects",
      images: [
        "/images/sample-products/p3-2.jpg",
        "/images/sample-products/p3-1.jpg",
      ],
      price: 649.99,
      brand: "Korg",
      rating: 4.7,
      numReviews: 28,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "KRK Rokit RP7 G4 Studio Monitor",
      slug: "krk-rokit-rp7-g4-studio-monitor",
      category: "Studio Monitors",
      description: "High-quality studio monitor with excellent bass response",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpeg",
      ],
      price: 249.99,
      brand: "KRK",
      rating: 4.5,
      numReviews: 19,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Moog Subharmonicon Semi-Modular Synth",
      slug: "moog-subharmonicon-semi-modular-synth",
      category: "Synthesizers",
      description:
        "Unique semi-modular synthesizer for rich, evolving patterns",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.webp",
      ],
      price: 699.99,
      brand: "Moog",
      rating: 4.9,
      numReviews: 14,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Akai MPC One Standalone Sampler",
      slug: "akai-mpc-one-standalone-sampler",
      category: "Samplers & Sequencers",
      description: "Compact and powerful standalone sampler and MIDI sequencer",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 899.99,
      brand: "Akai",
      rating: 4.8,
      numReviews: 26,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
